version: '3.9'

services:
  keycloakpoc:
    image: ${DOCKER_REGISTRY-}keycloakpoc
    build:
      context: .
      dockerfile: KeyCloakPOC/Dockerfile

  keycloak:
    image: quay.io/keycloak/keycloak:15.0.2
    container_name: keycloak
  
  keycloak-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: keycloak-db