apiVersion: v1
kind: Service
metadata:
  namespace: keycloakpoc-namespace
  name: keycloak-poc-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: keycloakpoc
    tier: app
    version: v1